### ISSUE TITLE
Question on BMS

### ISSUE THREAD

**Issue by gety9** [simat/BatteryMonitor#1]
Simat hi,

I am very interested in your BMS system. I was thinking to use cell log 8 + miniBMS set up for 24v 100ah battery pack. But miniBMS has 1 draw back - you can't modify LVC, and its default LVC is good for high C applications, in my situation 2.5v LVC cut of will mean not 80% DOD, but 95%+ DOD cause of low C rate.

Your BMS log can be accessed online, it's great feature, especially for the price.
I've read the 'Getting Started', i just have one question - can i use your BMS for LVC and HVC cut off?
If yes, could you please explain how it can be done.
In wiki i see only mentioning of cell logging, nothing about LVC and HVC.

Also what is the energy draw (ah) for the system.

Thank you for this interesting open source project!

**Comment by simat** [comment]
Yes you can use my battery monitor for LVC and HVC, at the end of the configuration file https://github.com/simat/BatteryMonitor/blob/master/battery8cell.cfg you will see a section for alarms. You can have as many alarms as you want. To create a new alarm just copy the one that is already there, rename it, select which output pin on the Beaglebone you want to use and what voltages you want the output to change at and what you want the output pin to do. You will need some sort of interface circuit, could be as simple as a resistor and transistor/mosfet to drive the cutoff relay.

I have measured the power draw from the battery manager to be 63mA at ~26 volts which equates to a daily draw of ~1.4 Ah/day

I agree that 2.5v for a LVC is too low. I have set mine to 2.8v. My output load can vary anything between 0.6C to nearly zero. The lowest voltage I have logged on my system is 3.04 which would have been at as SOC of 15-20%

Simon
